[general]
seed = 2020
output_folder = ""


[datasets]
  [datasets.bias]
    path = ""
    prompt_type = "no_change"
    [datasets.bias.demonstrations]
      [datasets.bias.demonstrations.zeroshot]
      [datasets.bias.demonstrations.random]
      shots = 10
      [datasets.bias.demonstrations.stratified]
      shots = 10
      [datasets.bias.demonstrations.within]
      shots = 10
      [datasets.bias.demonstrations.similarity]
      shots = 10
      [datasets.bias.demonstrations.diversity]
      shots = 10
    [datasets.bias.models]
      # [datasets.bias.models.gpt3]
      #   temperature = 1
      #   max_tokens = 5
      # [datasets.bias.models.chatgpt]
      #   temperature = 1
      #   max_tokens = 5
      # [datasets.bias.models.davinci-002]
      #   temperature = 1
      #   max_tokens = 5
      # [datasets.bias.models.offline-ul2]
      #   temperature = 1
      #   max_tokens = 5
      # [datasets.bias.models.flan-ul2]
      #   temperature = 1
      #   max_tokens = 5
      [datasets.bias.models.alpaca-13b]
        temperature = 1
        max_tokens = 5
      [datasets.bias.models.alpaca-7b]
        temperature = 1
        max_tokens = 5
      [datasets.bias.models.llama-13b]
        temperature = 1
        max_tokens = 5
      [datasets.bias.models.llama-65b]
        temperature = 1
        max_tokens = 5
      
  [datasets.aae]
    path = ""
    prompt_type = "no_change"
    [datasets.aae.demonstrations]
      [datasets.aae.demonstrations.random]
      shots = 10
      [datasets.aae.demonstrations.zeroshot]
      [datasets.aae.demonstrations.stratified]
      shots = 10
      [datasets.aae.demonstrations.within]
      shots = 10
      [datasets.aae.demonstrations.similarity]
      shots = 10
      [datasets.aae.demonstrations.diversity]
      shots = 10
  #   [datasets.aae.models]
  #     # [datasets.bias.models.gpt3]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.bias.models.chatgpt]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.bias.models.davinci-002]
  #     #   temperature = 1
  #     #   max_tokens = 5
      [datasets.aae.models.alpaca-13b]
        temperature = 1
        max_tokens = 5
      [datasets.aae.models.alpaca-7b]
        temperature = 1
        max_tokens = 5
      [datasets.aae.models.llama-13b]
        temperature = 1
        max_tokens = 5
      [datasets.aae.models.llama-65b]
        temperature = 1
        max_tokens = 5
  [datasets.hatexplain-race]
    path = ""
    [datasets.hatexplain-race.demonstrations]
      [datasets.hatexplain-race.demonstrations.random]
      shots = 10
      [datasets.hatexplain-race.demonstrations.similarity]
      shots = 10
      [datasets.hatexplain-race.demonstrations.zeroshot]
      [datasets.hatexplain-race.demonstrations.stratified]
      shots = 10
      [datasets.hatexplain-race.demonstrations.within]
      shots = 10
      [datasets.hatexplain-race.demonstrations.diversity]
      shots = 10
    [datasets.hatexplain-race.models]
  #     # [datasets.hatexplain-race.models.gpt3]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.hatexplain-race.models.chatgpt]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.hatexplain-race.models.ul2]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.hatexplain-race.models.flan-ul2]
  #     #   temperature = 1
  #     #   max_tokens = 5
      [datasets.hatexplain-race.models.alpaca-13b]
        temperature = 1
        max_tokens = 5
      [datasets.hatexplain-race.models.alpaca-7b]
        temperature = 1
        max_tokens = 5
      [datasets.hatexplain-race.models.llama-13b]
        temperature = 1
        max_tokens = 5
      [datasets.hatexplain-race.models.llama-65b]
        temperature = 1
        max_tokens = 5

  # [datasets.hatexplain-gender]
  #   path = ""
  #   [datasets.hatexplain-gender.demonstrations]
  #     [datasets.hatexplain-gender.demonstrations.random]
  #     shots = 10
  #     [datasets.hatexplain-gender.demonstrations.zeroshot]
  #     [datasets.hatexplain-gender.demonstrations.stratified]
  #     shots = 10
  #     [datasets.hatexplain-gender.demonstrations.within]
  #     shots = 10
  #     [datasets.hatexplain-gender.demonstrations.similarity]
  #     shots = 10
  #     [datasets.hatexplain-gender.demonstrations.diversity]
  #     shots = 10
  #   [datasets.hatexplain-gender.models]
  #     # [datasets.hatexplain-gender.models.gpt3]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.hatexplain-gender.models.chatgpt]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     # [datasets.hatexplain-gender.models.davinci-002]
  #     #   temperature = 1
  #     #   max_tokens = 5
  #     [datasets.hatexplain-gender.models.offline-ul2]
  #       temperature = 1
  #       max_tokens = 5
  #     [datasets.hatexplain-gender.models.flan-ul2]
  #       temperature = 1
  #       max_tokens = 5

  
      